import { describe, it, expect } from "vitest";
import { MUSIC_GAINS, SFX_GAINS, AUDIO_MEASUREMENTS, musicGain, sfxGain } from "@gameplay/AudioLevels";
import { MUSIC_FILES, SOUND_FILES, GameMusics, GameSounds } from "@gameplay/GameSounds";

/**
 * The generated loudness-correction table.
 *
 * `AudioLevels.ts` is generated by scripts/measure-audio-levels.mjs, so these
 * tests cannot check that the numbers are "right" in the abstract — they check
 * the invariants that make the numbers safe, which is what actually matters:
 * no gain may clip a track, and every id the game can ask for must resolve.
 */

describe("AudioLevels table", () => {
  it("never lets a music track clip", () => {
    // peak * gain <= 1.0 is the whole safety guarantee. Normalisation that
    // introduces clipping is worse than the unevenness it fixes.
    for (const [name, m] of Object.entries(AUDIO_MEASUREMENTS.music)) {
      expect(m.peak * m.gain, `${name} would clip`).toBeLessThanOrEqual(1.0 + 1e-6);
    }
  });

  it("never lets a sound effect clip", () => {
    for (const [name, m] of Object.entries(AUDIO_MEASUREMENTS.sfx)) {
      expect(m.peak * m.gain, `${name} would clip`).toBeLessThanOrEqual(1.0 + 1e-6);
    }
  });

  it("keeps every gain within the configured ceiling", () => {
    // MAX_GAIN in the generator is 3.0; a larger value would mean someone raised
    // the cap and started amplifying noise floors.
    for (const g of [...Object.values(MUSIC_GAINS), ...Object.values(SFX_GAINS)]) {
      expect(g).toBeGreaterThan(0);
      expect(g).toBeLessThanOrEqual(3.0);
    }
  });

  it("actually reduces the loudness spread it exists to fix", () => {
    const rmsSpread = (xs: number[]) => Math.max(...xs) / Math.min(...xs);
    const music = Object.values(AUDIO_MEASUREMENTS.music);

    const before = rmsSpread(music.map((m) => m.rms));
    const after = rmsSpread(music.map((m) => m.rms * m.gain));

    expect(before).toBeGreaterThan(2); // the source really is uneven
    expect(after).toBeLessThan(before);
    // Measured: 4.88x -> 1.71x. The residue is the peak-limited tracks, which
    // cannot be lifted further without clipping.
    expect(after).toBeLessThan(2.0);
  });

  it("boosts the quiet tracks and attenuates the loud ones", () => {
    const byLoudness = [...musicEntries()].sort((a, b) => a.rms - b.rms);
    const quietest = byLoudness[0];
    const loudest = byLoudness[byLoudness.length - 1];
    expect(quietest.gain).toBeGreaterThan(1);
    expect(loudest.gain).toBeLessThan(1);
  });
});

describe("AudioLevels lookup", () => {
  it("resolves a GameMusics id through MUSIC_FILES", () => {
    const id = GameMusics.ARMY;
    const file = MUSIC_FILES[id];
    expect(file).toBeDefined();
    expect(musicGain(id)).toBe(MUSIC_GAINS[file]);
    expect(musicGain(id)).toBeGreaterThan(0);
  });

  it("resolves every music id the game knows about", () => {
    for (const id of Object.values(MUSIC_FILES)) {
      expect(musicGain(id), `no gain for music id ${id}`).toBeGreaterThan(0);
    }
  });

  it("resolves every sound id the game knows about", () => {
    for (const id of Object.values(SOUND_FILES)) {
      expect(sfxGain(id), `no gain for sound id ${id}`).toBeGreaterThan(0);
    }
  });

  it("falls back to 1.0 for an unknown id rather than 0 or NaN", () => {
    // 1.0 means "no correction". Returning 0 would silence a new track added
    // before the table is regenerated; NaN would poison the gain node.
    expect(musicGain("no such track")).toBe(1.0);
    expect(sfxGain("no such sound")).toBe(1.0);
  });

  it("returns a finite number for a known GameMusics constant", () => {
    expect(Number.isFinite(musicGain(GameMusics.LIMBO))).toBe(true);
    expect(Number.isFinite(sfxGain(GameSounds.UNDEAD_EAT))).toBe(true);
  });
});

describe("SFX gain policy", () => {
  it("peak-normalises, so the quietest effect gets the biggest boost", () => {
    // SFX are normalised on peak, not RMS: "undead eat" has a peak of 0.39
    // against 1.0 for "nightmare", and it is simply recorded quiet.
    const all = Object.values(AUDIO_MEASUREMENTS.sfx);
    const quietest = all.reduce((a, b) => (a.peak <= b.peak ? a : b));
    const loudest = all.reduce((a, b) => (a.peak >= b.peak ? a : b));
    expect(quietest.gain).toBeGreaterThan(loudest.gain);
    for (const m of all) {
      // Every sfx ends up at the same peak.
      expect(m.peak * m.gain).toBeCloseTo(0.95, 1);
    }
  });
});

function musicEntries(): Array<{ rms: number; gain: number; peak: number }> {
  return Object.values(AUDIO_MEASUREMENTS.music);
}
