import { beforeAll, describe, expect, it } from "vitest";

import { District, DistrictKind } from "@data/District";
import { Lighting, Map as GameMap } from "@data/Map";
import { Models } from "@data/Models";
import { DiceRoller } from "@engine/DiceRoller";
import { Point } from "@engine/Point";
import { Rules } from "@engine/Rules";
import { Ruleset, Session } from "@engine/Session";
import { Car, PowerGenerator } from "@engine/mapobjects/MapObjects";
import { GameActors } from "@gameplay/GameActors";
import { GameFactions } from "@gameplay/GameFactions";
import { GameImages } from "@gameplay/GameImages";
import { GameItems } from "@gameplay/GameItems";
import { GameTiles, TileID } from "@gameplay/GameTiles";
import { BaseTownGenerator, Parameters } from "@gameplay/generators/BaseTownGenerator";

/**
 * The mall's two linked levels: the food court / supermarket / two cinemas upstairs,
 * and the car park below.
 *
 * `tests/shopping-mall-building.test.ts` covers the ground floor, the district's block
 * layout and the six stair pairs, and asserts of the two levels only that they are
 * 51x51 and that the far ends of the exits exist. Everything that is *on* them is
 * here, and the shape of the file is the same as that one's: the **real**
 * `BaseTownGenerator.generate()` is driven with `Parameters.generateShoppingMall` on,
 * because a level generated by calling `generateShoppingMallUpperLevel` directly would
 * be a level with no exits on it and would not catch a stairway landing in a wall.
 *
 * What is asserted, and why these and not something tidier:
 *
 * 1. **The upper level's four regions by name and bounds.** `food court` over
 *    `(1, 1, 25, 22)` and `Supermarket` over `(26, 1, 25, 22)` are the C#'s two
 *    `MakeUniqueZone` calls (`:10205`, `:10302`); the bathrooms and the cinema foyer get
 *    **no zone at all**, which is the reference's own asymmetry and is what the
 *    corridor, the auditoria and the cubicles having no name means.
 * 2. **The pool is real water, and `hasWaterTiles` is true.** The flag's only reason in
 *    the C# (`:10189`) is the pool at `:10277-10278`, so the two are asserted together:
 *    a port that set the flag without the tiles would pass either assertion alone.
 * 3. **The parking bays are `PARKING_ASPHALT_NS` on the two edge rows and
 *    `PARKING_ASPHALT_EW` everywhere else**, which is the C#'s orientation and the one
 *    thing about this method a reader cannot guess: the two models are not
 *    interchangeable and the abandoned-car test at `:10599` accepts both.
 * 4. **The pillars and railings alternate on a five-step cycle**, and the pillar is a
 *    *tile* while the railing is a *map object* — five pillars and sixteen railings per
 *    column, sixteen columns.
 * 5. **The two power rooms are empty.** `CountAdjWalls >= 3` is unreachable in either
 *    of them, so the generator places no `power generator` at all while still creating
 *    the two `power room` zones. Asserted because it reads like a bug and *is* the
 *    C#'s arithmetic; a port that "fixed" it would fail here.
 * 6. **The stair columns still land on floor**, now that both levels have furniture: the
 *    ground floor's six exits have to arrive somewhere that is neither a wall nor a
 *    shelf, and the exits are added *after* generation, so this is the only place that
 *    can catch a level filling its own doorway.
 */

const SEED = 1;

/** `DEFAULT_DISTRICT_SIZE` — the same default the ground-floor file generates at. */
const DISTRICT_SIZE = 50;

const rules = new Rules(new DiceRoller(20250929));
beforeAll(() => {
  new GameTiles();
  new GameActors();
  new GameItems();
  new GameFactions();
});

function newParams(): Parameters {
  const params = new Parameters();
  params.district = new District(new Point(0, 0), DistrictKind.SHOPPING);
  params.mapWidth = params.mapHeight = DISTRICT_SIZE;
  params.generateShoppingMall = true;
  return params;
}

/**
 * Generate a real mall district and hand back the two levels, by name.
 *
 * `District.entryMap` is installed *after* generation, exactly as
 * `GenerateDistrictEntryMap` does at `RogueGame.cs:5008-5014`, so the two linked maps
 * are the first two entries of `district.maps` and the surface map is the third.
 */
function generateLevels(seed = SEED): { upper: GameMap; parking: GameMap; ground: GameMap; district: District } {
  const district = new District(new Point(0, 0), DistrictKind.SHOPPING);
  const params = newParams();
  params.district = district;
  const ground = new BaseTownGenerator({ rules, ApplyOnFire: () => undefined } as never, params).generate(seed);
  district.entryMap = ground;

  const upper = district.maps.find((m) => m.name === "Shopping Mall - Upper Level");
  const parking = district.maps.find((m) => m.name === "Shopping Mall - Parking");
  if (!upper || !parking) throw new Error("the mall did not link its two levels");
  return { upper, parking, ground, district };
}

function modelAt(map: GameMap, x: number, y: number) {
  return map.getTileAt(x, y)!.model;
}

function objAt(map: GameMap, x: number, y: number) {
  return map.getMapObjectAt(x, y);
}

/** Every tile whose map object satisfies `keep`, as `[x, y]`. */
function objectsWhere(map: GameMap, keep: (name: string, imageId: string) => boolean): [number, number][] {
  const out: [number, number][] = [];
  for (let x = 0; x < map.width; x++) {
    for (let y = 0; y < map.height; y++) {
      const obj = objAt(map, x, y);
      if (obj && keep(obj.name, obj.imageId)) out.push([x, y]);
    }
  }
  return out;
}

/** Two hashes over tile models, objects, decorations, `isInside` and ground stacks. */
function fingerprint(map: GameMap): string {
  let h1 = 0x811c9dc5;
  let h2 = 0x01000193;
  for (let x = 0; x < map.width; x++) {
    for (let y = 0; y < map.height; y++) {
      const tile = map.getTileAt(x, y)!;
      const obj = objAt(map, x, y);
      const stack = map.getItemsAt(new Point(x, y));
      const cell = `${tile.model.id}|${obj ? obj.imageId : "-"}|${(tile.getDecorations ?? []).join(",")}|${
        tile.isInside ? 1 : 0
      }|${stack ? stack.countItems : 0}`;
      for (let i = 0; i < cell.length; i++) {
        h1 = Math.imul(h1 ^ cell.charCodeAt(i), 16777619) >>> 0;
        h2 = (Math.imul(h2 + cell.charCodeAt(i) + i, 2654435761) ^ (h2 >>> 7)) >>> 0;
      }
    }
  }
  return h1.toString(16).padStart(8, "0") + h2.toString(16).padStart(8, "0");
}

// ── The C#'s coordinates, transcribed ────────────────────────────────────────

/** C# `:10208` — the counter row: 24 tiles across `y == 2`, `x` 1 through 24. */
const COUNTER_ROW = Array.from({ length: 24 }, (_, i) => [1 + i, 2] as const);

/** C# `:10251-10253` — twenty food-court tables, on the C#'s own four-by-five grid. */
const FOOD_COURT_TABLES: readonly (readonly [number, number])[] = [
  [3, 7], [3, 11], [3, 15], [3, 19], [7, 7], [7, 11], [7, 15], [7, 19], [11, 7], [11, 19], [16, 7], [16, 19],
  [20, 7], [20, 11], [20, 15], [20, 19], [24, 7], [24, 11], [24, 15], [24, 19],
];

/** C# `:10277` — the water itself, `(12, 12, 4, 3)`. */
const POOL_RECT = { left: 12, top: 12, width: 4, height: 3 } as const;

/** C# `:10351-10358` — eight supermarket checkouts, every other `x` from 34 to 48. */
const SUPERMARKET_CHECKOUTS: readonly (readonly [number, number])[] = [
  [34, 20], [36, 20], [38, 20], [40, 20], [42, 20], [44, 20], [46, 20], [48, 20],
];

/** C# `:10441-10443` — the eight auditorium doorways in the `y == 32` curtain row. */
const CINEMA_DOORS: readonly (readonly [number, number])[] = [
  [3, 32], [4, 32], [23, 32], [24, 32], [28, 32], [29, 32], [47, 32], [48, 32],
];

/** C# `:10449-10452` — `CINEMA2` on the west auditorium, `CINEMA1` on the east. */
const CINEMA_SIGNS: readonly (readonly [number, string])[] = [
  [5, GameImages.DECO_CINEMA2],
  [22, GameImages.DECO_CINEMA2],
  [30, GameImages.DECO_CINEMA1],
  [46, GameImages.DECO_CINEMA1],
];

/** C# `:10578-10581` — the sixteen bay columns: eight north of the lanes, eight south. */
const PARKING_COLUMNS: readonly (readonly [number, number])[] = [
  [9, 4], [14, 4], [19, 4], [24, 4], [29, 4], [34, 4], [39, 4], [44, 4],
  [9, 27], [14, 27], [19, 27], [24, 27], [29, 27], [34, 27], [39, 27], [44, 27],
];

/** C# `:10512-10517` — three two-tile doorways through the `x == 4` separating wall. */
const PARKING_OPENINGS: readonly (readonly [number, number])[] = [
  [4, 15], [4, 16], [4, 25], [4, 26], [4, 35], [4, 36],
];

describe("Feature.ShoppingMall — the upper level", () => {
  it("is a dark indoor 51x51 with water, and two zones and nothing more", () => {
    Session.get().ruleset = Ruleset.STILL_ALIVE;
    const { upper } = generateLevels();

    expect(upper.name).toBe("Shopping Mall - Upper Level");
    expect(upper.width).toBe(51);
    expect(upper.height).toBe(51);
    expect(upper.lighting).toBe(Lighting.DARKNESS);
    // `DoForEachTile(map.Rect, (pt) => map.GetTileAt(pt).IsInside = true)` (`:10191`),
    // asserted wholesale: a level with a single un-indoors tile is a level whose
    // lighting does not apply there.
    for (let x = 0; x < 51; x++) {
      for (let y = 0; y < 51; y++) expect(upper.getTileAt(x, y)!.isInside, `${x},${y}`).toBe(true);
    }

    // **Two zones, and their bounds are the C#'s.** `food court` is `Rectangle(1,1,25,22)`
    // and `Supermarket` is `Rectangle(26,1,25,22)` — together the whole northern
    // 25-row band, which is what makes the central row and the cinemas zoneless.
    const zones = upper.zones.map((z) => ({ name: z.name, bounds: z.bounds }));
    expect(zones).toHaveLength(2);
    expect(zones[0]!.name.startsWith("food court@")).toBe(true);
    expect(zones[0]!.bounds.left).toBe(1);
    expect(zones[0]!.bounds.top).toBe(1);
    expect(zones[0]!.bounds.width).toBe(25);
    expect(zones[0]!.bounds.height).toBe(22);
    expect(zones[1]!.name.startsWith("Supermarket@")).toBe(true);
    expect(zones[1]!.bounds.left).toBe(26);
    expect(zones[1]!.bounds.top).toBe(1);
    expect(zones[1]!.bounds.width).toBe(25);
    expect(zones[1]!.bounds.height).toBe(22);
  });

  it("has a ring of real water with a dry island for the palm trees, and says so on the map", () => {
    Session.get().ruleset = Ruleset.STILL_ALIVE;
    const { upper } = generateLevels();

    // **The two assertions together.** `HasWaterTiles = true` (`:10189`) and
    // `FLOOR_FOOD_COURT_POOL` (`:10278`) are only meaningful as a pair; either alone
    // is a lie the reader cannot see.
    expect(upper.hasWaterTiles).toBe(true);
    const pool = Models.tiles.get(TileID.FLOOR_FOOD_COURT_POOL)!;
    expect(pool.isWater, "the pool model is registered as water").toBe(true);
    // The ring itself: two rows of four plus the two side tiles between them.
    for (let x = POOL_RECT.left; x < POOL_RECT.left + POOL_RECT.width; x++) {
      expect(modelAt(upper, x, POOL_RECT.top), `pool north ${x}`).toBe(pool);
      expect(modelAt(upper, x, POOL_RECT.top + POOL_RECT.height - 1), `pool south ${x}`).toBe(pool);
    }
    expect(modelAt(upper, POOL_RECT.left, POOL_RECT.top + 1), "pool west").toBe(pool);
    expect(modelAt(upper, POOL_RECT.left + POOL_RECT.width - 1, POOL_RECT.top + 1), "pool east").toBe(pool);
    // **`TileRectangle`, not `TileFill` (`:10278`)** — the pool is a one-tile-wide ring of
    // ten water tiles and `(13, 13)` / `(14, 13)` are still the white tile the shell laid.
    // That is the only reason "palm tree in the middle" means anything at all.
    const white = Models.tiles.get(TileID.FLOOR_WHITE_TILE)!;
    for (const [x, y] of [[13, 13], [14, 13]] as [number, number][]) {
      expect(modelAt(upper, x, y), `pool island ${x},${y} is dry`).toBe(white);
    }
    let waterTiles = 0;
    for (let x = 0; x < 51; x++) {
      for (let y = 0; y < 51; y++) if (modelAt(upper, x, y) === pool) waterTiles++;
    }
    expect(waterTiles, "ten water tiles, not twelve").toBe(10);

    // The concrete surround is `Rectangle(11, 11, 6, 5)` (`:10269`) — a perimeter, so one
    // tile of it on every side, and a potted plant on each of its four corners.
    const concrete = Models.tiles.get(TileID.FLOOR_CONCRETE)!;
    for (const [x, y] of [[11, 11], [11, 15], [16, 11], [16, 15]] as [number, number][]) {
      expect(modelAt(upper, x, y), `pool corner ${x},${y}`).toBe(concrete);
      expect(objAt(upper, x, y)?.name, `pool corner plant ${x},${y}`).toBe("potted plant");
    }
    // And the two palm trees are `MakeObjTree`, so breakable *and* a wood source.
    for (const [x, y] of [[13, 13], [14, 13]] as [number, number][]) {
      const palm = objAt(upper, x, y);
      expect(palm?.name, `palm tree ${x},${y}`).toBe("tree");
      expect(palm?.imageId).toBe(GameImages.OBJ_FOOD_COURT_PALM_TREE);
      expect(palm?.givesWood, "a palm tree is a wood source").toBe(true);
    }
  });

  it("has twenty-four counters, each with a price board behind it and something on it", () => {
    Session.get().ruleset = Ruleset.STILL_ALIVE;
    const { upper } = generateLevels();

    const COUNTER_SPRITES = new Set([
      GameImages.OBJ_FOOD_COURT_COUNTER1,
      GameImages.OBJ_FOOD_COURT_COUNTER2,
      GameImages.OBJ_FOOD_COURT_COUNTER3,
      GameImages.OBJ_FOOD_COURT_COUNTER4,
      GameImages.OBJ_FOOD_COURT_COUNTER5,
    ]);
    const BOARD_SPRITES = new Set([
      GameImages.DECO_FOOD_COURT_PRICEBOARD1,
      GameImages.DECO_FOOD_COURT_PRICEBOARD2,
      GameImages.DECO_FOOD_COURT_PRICEBOARD3,
      GameImages.DECO_FOOD_COURT_PRICEBOARD4,
      GameImages.DECO_FOOD_COURT_PRICEBOARD5,
    ]);
    // The Release 7-6 counter roll at `:10236`, `Roll(0, 4)` over four arms.
    const COUNTER_ITEMS = new Set([
      GameImages.ITEM_COOKED_CHICKEN,
      GameImages.ITEM_FRYING_PAN,
      GameImages.ITEM_CLEAVER,
      GameImages.ITEM_KITCHEN_KNIFE,
    ]);

    expect(COUNTER_ROW).toHaveLength(24);
    for (const [x, y] of COUNTER_ROW) {
      const counter = objAt(upper, x, y);
      expect(counter?.name, `counter at ${x},${y}`).toBe("counter");
      expect(COUNTER_SPRITES.has(counter!.imageId), `counter sprite at ${x},${y}`).toBe(true);

      // **Exactly one item per counter**, and one of exactly four kinds. The C#'s
      // `DropItemAt` runs before `MakeObjCounter` is offered and `MapObjectFill` then
      // places unconditionally, so the item and the counter are independent — which is
      // only observable because every one of these 24 tiles is free.
      const items = upper.getItemsAt(new Point(x, y));
      expect(items?.countItems, `counter items at ${x},${y}`).toBe(1);
      expect(COUNTER_ITEMS.has(items!.getItem(0)!.model.imageId), `counter item at ${x},${y}`).toBe(true);

      // The board is two tiles north, on the **perimeter wall** (`:10221`) — asserted as
      // a wall tile so "two tiles up" cannot quietly become "two tiles up onto floor".
      const boardTile = upper.getTileAt(x, y - 2)!;
      expect(boardTile.model, `price board is on the north wall at ${x}`).toBe(
        Models.tiles.get(TileID.WALL_MALL),
      );
      expect((boardTile.getDecorations ?? []).length, `price board decoration at ${x}`).toBe(1);
      expect(BOARD_SPRITES.has(boardTile.getDecorations![0]!), `price board sprite at ${x}`).toBe(true);
    }
    // Exactly 24 of each, so "every counter has one" is a fact about the counters rather
    // than about the whole room.
    expect(objectsWhere(upper, (name) => name === "counter")).toHaveLength(24);
  });

  it("has twenty food-court tables with a chair at each of the four cardinals", () => {
    Session.get().ruleset = Ruleset.STILL_ALIVE;
    const { upper } = generateLevels();

    expect(FOOD_COURT_TABLES).toHaveLength(20);
    for (const [x, y] of FOOD_COURT_TABLES) {
      expect(objAt(upper, x, y)?.imageId, `table at ${x},${y}`).toBe(GameImages.OBJ_FOOD_COURT_TABLE);
      for (const [dx, dy] of [[0, -1], [1, 0], [0, 1], [-1, 0]] as const) {
        const chair = objAt(upper, x + dx, y + dy);
        expect(chair?.imageId, `chair at ${x + dx},${y + dy}`).toBe(GameImages.OBJ_FOOD_COURT_CHAIR);
        // **The food court's own `MakeObjChair`, not the cinema's `MakeObjSeat`.** Same
        // four-neighbour layout, different sprite and different name, and the two
        // factories are `UNINFLAMMABLE` against `BURNABLE` — the cheapest place to catch
        // one factory standing in for the other.
        expect(chair?.name).toBe("chair");
        expect(chair?.isFlammable).toBe(false);
      }
    }
    // 20 tables + 80 chairs, and no chair anywhere else. The five-tile spacing of the
    // `tablePoints` grid is what makes 80 exact rather than "at most 80".
    expect(objectsWhere(upper, (name) => name === "table")).toHaveLength(20);
    expect(objectsWhere(upper, (name) => name === "chair")).toHaveLength(80);
  });

  it("fills the supermarket with shelf aisles, a clear centre aisle and eight checkouts", () => {
    Session.get().ruleset = Ruleset.STILL_ALIVE;
    const { upper } = generateLevels();

    // `TileFill(FLOOR_TILES, new Rectangle(27, 2, 23, 20))` (`:10301`).
    const tiles = Models.tiles.get(TileID.FLOOR_TILES)!;
    expect(modelAt(upper, 27, 2), "supermarket floor").toBe(tiles);
    expect(modelAt(upper, 49, 21), "supermarket floor, far corner").toBe(tiles);
    // The storefront's own two decorations at `x` 27 and 33 (`y == 22`), and the five
    // white tiles between them are the doorway (`:10304-10306`).
    for (const x of [27, 33]) {
      expect(upper.getTileAt(x, 22)!.getDecorations, `grocery sign at ${x},22`).toContain(
        GameImages.DECO_SHOP_GROCERY,
      );
    }
    const white = Models.tiles.get(TileID.FLOOR_WHITE_TILE)!;
    for (const x of [28, 29, 30, 31, 32]) expect(modelAt(upper, x, 22), `doorway ${x},22`).toBe(white);
    expect(modelAt(upper, 27, 22)).not.toBe(white);
    expect(modelAt(upper, 33, 22)).not.toBe(white);

    // **The alley walk, asserted as the C# computes it** rather than as a count:
    // `Rectangle(27, 2, 23, 17)` is wider than tall, so the shelves go on the odd rows
    // and the aisle at `27 + 23 / 2 == 38` is left clear. `FromLTRB(28, 2, 49, 19)`.
    const centralAlley = 38;
    let shelves = 0;
    for (let x = 28; x < 49; x++) {
      for (let y = 2; y < 19; y++) {
        const want = (y - 2) % 2 === 1 && x !== centralAlley;
        const obj = objAt(upper, x, y);
        if (want) {
          expect(obj?.name, `shelf at ${x},${y}`).toBe("shelf");
          expect(obj?.imageId).toBe(GameImages.OBJ_SHOP_SHELF);
          shelves++;
        } else {
          expect(obj, `nothing at ${x},${y}`).toBeNull();
        }
      }
    }
    // 21 columns less the centre aisle, on eight odd rows.
    expect(shelves).toBe(8 * 20);
    // Every shelf carries a grocery item — dropped *before* the shelf is offered, which
    // is why the count matches even though the offer is what puts the object down.
    for (let x = 28; x < 49; x++) {
      for (let y = 2; y < 19; y++) {
        if ((y - 2) % 2 !== 1 || x === centralAlley) continue;
        expect(upper.getItemsAt(new Point(x, y))?.countItems, `grocery at ${x},${y}`).toBe(1);
      }
    }

    // Eight checkouts on `y == 20`, every other tile.
    expect(SUPERMARKET_CHECKOUTS).toHaveLength(8);
    for (const [x, y] of SUPERMARKET_CHECKOUTS) {
      const checkout = objAt(upper, x, y);
      expect(checkout?.name, `checkout at ${x},${y}`).toBe("checkout");
      // **`OBJ_SUPERMARKET_CHECKOUT`, not `OBJ_CLINIC_DESK`.** The ground floor's eleven
      // registers use the clinic sprite (`:9978`); these eight are the mall's own, and
      // one sprite with two names is a decision worth pinning.
      expect(checkout?.imageId).toBe(GameImages.OBJ_SUPERMARKET_CHECKOUT);
    }
    expect(objectsWhere(upper, (name, imageId) => name === "checkout" && imageId === GameImages.OBJ_SUPERMARKET_CHECKOUT)).toHaveLength(8);
  });

  it("has two public bathrooms whose door column is walled over", () => {
    Session.get().ruleset = Ruleset.STILL_ALIVE;
    const { upper } = generateLevels();

    const wallMall = Models.tiles.get(TileID.WALL_MALL)!;
    // `:10363-10371`. Two cubicles at `x` 1-2, doors in the `x == 3` column, and the
    // tile *under* each door's own row turned into wall.
    for (const y of [23, 28]) {
      const door = objAt(upper, 3, y);
      expect(door?.name, `bathroom door at 3,${y}`).toBe("wooden door");
    }
    for (const y of [24, 27]) {
      expect(objAt(upper, 1, y)?.name, `toilet at 1,${y}`).toBe("toilet");
      expect(objAt(upper, 2, y)?.name, `basin at 2,${y}`).toBe("basin");
      // The door column is wall on these two rows and *not* on the rows above and below.
      expect(modelAt(upper, 3, y), `wall at 3,${y}`).toBe(wallMall);
    }
    // The two-row divider, and the two cubicle mouths that survive it.
    for (const y of [25, 26]) {
      for (const x of [1, 2, 3]) expect(modelAt(upper, x, y), `divider ${x},${y}`).toBe(wallMall);
    }
    // **No zone.** The bathrooms are inside the `food court` zone's bounding rect by one
    // row of overlap and outside it by the rest, and the C# gives them none of their own —
    // which is the reference's asymmetry, not a gap.
    expect(upper.zones.some((z) => z.name.startsWith("bathroom"))).toBe(false);
    expect(upper.zones.some((z) => z.name.startsWith("cinema"))).toBe(false);
  });

  it("has a cinema foyer that opens into the corridor through three tiles", () => {
    Session.get().ruleset = Ruleset.STILL_ALIVE;
    const { upper } = generateLevels();

    // `TileFill(FLOOR_RED_CARPET, new Rectangle(42, 23, 8, 6))` (`:10407`).
    const carpet = Models.tiles.get(TileID.FLOOR_RED_CARPET)!;
    expect(modelAt(upper, 42, 23), "foyer floor").toBe(carpet);
    expect(modelAt(upper, 49, 28), "foyer floor, far corner").toBe(carpet);

    // Six reception desks in one column against the east wall, drawn with the *bank's*
    // teller sprite (`:10408-10413`) — one sprite, two names, as the mall's registers do
    // with the clinic desk.
    for (let y = 23; y <= 28; y++) {
      const desk = objAt(upper, 48, y);
      expect(desk?.name, `reception desk at 48,${y}`).toBe("reception desk");
      expect(desk?.imageId).toBe(GameImages.OBJ_BANK_TELLER);
      expect(desk?.isContainer, "a reception desk holds things").toBe(true);
    }
    // Seven couches: four on the north side of the entry, three on the south. Collected in
    // scan order (`x` outer) and compared as a whole, so "four and three" is stated
    // rather than implied by a count of seven.
    const foyerCouches: [number, number][] = [];
    for (let x = 42; x < 50; x++) {
      for (let y = 23; y < 29; y++) {
        if (objAt(upper, x, y)?.imageId === GameImages.OBJ_COUCH) foyerCouches.push([x, y]);
      }
    }
    expect(foyerCouches).toEqual([
      [42, 23], [42, 28], [43, 23], [43, 28], [44, 23], [44, 28], [45, 23],
    ]);
    // The ticket check: a *drawer*, the only thing in the foyer that is not a couch or a
    // desk, and it sits at `(46, 29)` — i.e. in the corridor mouth, not in the foyer.
    const drawer = objAt(upper, 46, 29);
    expect(drawer?.name).toBe("drawer");
    expect(drawer?.imageId).toBe(GameImages.OBJ_LECTERN);
    expect(modelAt(upper, 46, 29), "the ticket check stands on the corridor entry").toBe(carpet);

    // **The corridor wall at `y == 29` spans `x` 1-50 and has exactly three holes**, at
    // `x` 45-47 (`:10426`, `:10428`), which is what makes the foyer reachable.
    const wall = Models.tiles.get(TileID.WALL_MALL)!;
    for (const x of [1, 20, 44, 48, 50]) expect(modelAt(upper, x, 29), `corridor wall ${x},29`).toBe(wall);
    for (const x of [45, 46, 47]) expect(modelAt(upper, x, 29), `corridor entry ${x},29`).toBe(carpet);
  });

  it("runs two auditoria off one corridor, with the west one signed CINEMA2", () => {
    Session.get().ruleset = Ruleset.STILL_ALIVE;
    const { upper } = generateLevels();

    // `TileFill(FLOOR_RED_CARPET, new Rectangle(1, 30, 49, 20))` — corridor and both
    // auditoria — then five runs of `WALL_RED_CURTAINS` over it.
    const carpet = Models.tiles.get(TileID.FLOOR_RED_CARPET)!;
    const curtains = Models.tiles.get(TileID.WALL_RED_CURTAINS)!;
    expect(modelAt(upper, 2, 30), "corridor floor").toBe(carpet);
    expect(modelAt(upper, 2, 49), "auditorium floor").toBe(carpet);
    // The left wall, the bottom wall, the right wall, the auditorium top wall and the
    // dividing wall — `x` 26 runs the full height of the cinema block, which is what
    // splits it into two.
    for (let y = 30; y <= 50; y++) {
      expect(modelAt(upper, 1, y), `left curtain 1,${y}`).toBe(curtains);
      expect(modelAt(upper, 50, y), `right curtain 50,${y}`).toBe(curtains);
    }
    for (let x = 1; x <= 50; x++) expect(modelAt(upper, x, 50), `bottom curtain ${x},50`).toBe(curtains);
    // The auditorium top wall, less the eight doorways it is about to be punched through —
    // the curtain row is asserted *before* the doors below, so the eight door `x` values
    // are excluded here and asserted as carpet afterwards.
    const doorXs = new Set(CINEMA_DOORS.map(([x]) => x));
    for (let x = 1; x <= 50; x++) {
      if (doorXs.has(x)) continue;
      expect(modelAt(upper, x, 32), `top curtain ${x},32`).toBe(curtains);
    }
    for (let y = 32; y <= 50; y++) expect(modelAt(upper, 26, y), `divider curtain 26,${y}`).toBe(curtains);
    // The four corridor bins, two either end, in the two rows that are corridor and not
    // auditorium (`:10436-10439`).
    for (const [x, y] of [[2, 30], [2, 31], [49, 30], [49, 31]] as [number, number][]) {
      expect(objAt(upper, x, y)?.name, `corridor bin ${x},${y}`).toBe("receptacle");
    }

    // Eight doorways punched through the `y == 32` curtain row, four per auditorium, and
    // the tile under each one turned back to carpet so the door is not in a wall.
    expect(CINEMA_DOORS).toHaveLength(8);
    for (const [x, y] of CINEMA_DOORS) {
      expect(modelAt(upper, x, y), `door tile ${x},${y}`).toBe(carpet);
      expect(objAt(upper, x, y)?.name, `cinema door ${x},${y}`).toBe("wooden door");
    }
    // **The numbering agrees with the signs and only the widths differ.**
    // `DECO_CINEMA2` signposts the west auditorium (`x` 5 and 22) and `DECO_CINEMA1` the
    // east (`x` 30 and 46); `cinema2Screen` is the west rectangle and `cinema1Screen` the
    // east, so `1` is the east room on both counts. The asymmetry is *size*: cinema1 gets
    // a 21-tile screen and 19-seat rows against cinema2's 22 and 20, which is what
    // `//cinema1, slightly smaller` at `:10460` is about.
    for (const [x, deco] of CINEMA_SIGNS) {
      expect(upper.getTileAt(x, 32)!.model, `sign tile ${x},32`).toBe(curtains);
      expect(upper.getTileAt(x, 32)!.getDecorations, `sign ${x},32`).toContain(deco);
    }
    expect(upper.getTileAt(5, 32)!.getDecorations).not.toContain(GameImages.DECO_CINEMA1);
    expect(upper.getTileAt(30, 32)!.getDecorations).not.toContain(GameImages.DECO_CINEMA2);

    // **Seats: six rows of twenty on the west and six of nineteen on the east** — the
    // `rowWidth = 19` for `rowstartPoint.Key == 29` is the C#'s own comment, "cinema1,
    // slightly smaller". The numbers are asserted as arithmetic so the asymmetry is
    // visible rather than as a bare total.
    const seats = objectsWhere(upper, (name) => name === "seat");
    expect(seats).toHaveLength(6 * 20 + 6 * 19);
    for (const y of [34, 36, 38, 40, 42, 44]) {
      for (let x = 4; x < 24; x++) expect(objAt(upper, x, y)?.name, `west seat ${x},${y}`).toBe("seat");
      expect(objAt(upper, 3, y), `west row starts at x+4, not x+3 (${y})`).toBeNull();
      for (let x = 29; x < 48; x++) expect(objAt(upper, x, y)?.name, `east seat ${x},${y}`).toBe("seat");
      expect(objAt(upper, 28, y), `east row starts at x+29, not x+28 (${y})`).toBeNull();
      expect(objAt(upper, 48, y), `east row is 19 wide, not 20 (${y})`).toBeNull();
    }
    // A cinema seat is burnable; the food court's chair is not. Pinned separately because
    // it is the cheapest way to see the two factories are not interchangeable.
    expect(objAt(upper, 4, 34)?.isFlammable).toBe(true);
    expect(objectsWhere(upper, (name, imageId) => name === "seat" && imageId !== GameImages.OBJ_CINEMA_SEAT)).toEqual([]);

    // **Screens: 21 on the east (`x` 28-48) and 22 on the west (`x` 3-24)**, one tile
    // high at `y == 49`, and the two runs do not meet — `x == 26` is the dividing curtain
    // and `x` 25 and 27 are its shoulders.
    const screens = objectsWhere(upper, (name) => name === "screen");
    expect(screens).toHaveLength(43);
    for (const x of [3, 24]) expect(objAt(upper, x, 49)?.name, `west screen ${x},49`).toBe("screen");
    for (const x of [28, 48]) expect(objAt(upper, x, 49)?.name, `east screen ${x},49`).toBe("screen");
    expect(objAt(upper, 2, 49), "the west screen starts at x+3").toBeNull();
    expect(objAt(upper, 25, 49), "no screen at x+25").toBeNull();
    expect(objAt(upper, 27, 49), "no screen at x+27").toBeNull();
    expect(objAt(upper, 49, 49), "the east screen stops at x+48").toBeNull();
    // A screen is the one object in the mall with no flags at all.
    const screen = objAt(upper, 3, 49)!;
    expect(screen.isMaterialTransparent).toBe(false);
    expect(screen.isJumpable).toBe(false);
    expect(screen.givesWood).toBe(false);
  });
});

describe("Feature.ShoppingMall — the parking level", () => {
  it("is a dark indoor 51x51 of asphalt with a walkway strip and three doorways", () => {
    Session.get().ruleset = Ruleset.STILL_ALIVE;
    const { parking } = generateLevels();

    expect(parking.name).toBe("Shopping Mall - Parking");
    expect(parking.width).toBe(51);
    expect(parking.height).toBe(51);
    expect(parking.lighting).toBe(Lighting.DARKNESS);
    for (let x = 0; x < 51; x++) {
      for (let y = 0; y < 51; y++) expect(parking.getTileAt(x, y)!.isInside, `${x},${y}`).toBe(true);
    }

    // The shell: asphalt everywhere, a five-wide walkway strip down the west, and a
    // concrete perimeter.
    const asphalt = Models.tiles.get(TileID.FLOOR_ASPHALT)!;
    const walkway = Models.tiles.get(TileID.FLOOR_WALKWAY)!;
    const concrete = Models.tiles.get(TileID.WALL_CONCRETE)!;
    expect(modelAt(parking, 7, 3), "car park floor").toBe(asphalt);
    // **The walkway strip is five wide (`x` 1-5) and the separating wall is the *fourth*
    // of those five**, so `x == 5` is walkway and the car park proper starts at `x == 6` —
    // the wall sits inside the strip rather than being its east edge.
    expect(modelAt(parking, 3, 3), "entry walkway").toBe(walkway);
    expect(modelAt(parking, 5, 3), "the strip's fifth column").toBe(walkway);
    expect(modelAt(parking, 6, 3), "car park floor, east of the separator").toBe(asphalt);
    for (const [x, y] of [[0, 25], [25, 0], [50, 25], [25, 50]] as [number, number][]) {
      expect(modelAt(parking, x, y), `perimeter ${x},${y}`).toBe(concrete);
    }

    // The `x == 4` separator runs the whole height except six tiles, in three pairs.
    for (const y of [1, 14, 17, 24, 27, 34, 37, 49]) {
      expect(modelAt(parking, 4, y), `separator ${4},${y}`).toBe(concrete);
    }
    expect(PARKING_OPENINGS).toHaveLength(6);
    for (const [x, y] of PARKING_OPENINGS) {
      expect(modelAt(parking, x, y), `opening ${x},${y}`).toBe(walkway);
    }

    // The fourteen pieces of walkway furniture in the `x == 1` column: four bins, four
    // plants, six benches, and **nothing at all at `y` 23-28** — which is where the
    // ground floor's two stairs land.
    const bins = objectsWhere(parking, (name, imageId) => name === "receptacle" && imageId === GameImages.OBJ_EMPTY_BIN);
    expect(bins).toEqual([[1, 16], [1, 22], [1, 29], [1, 35]]);
    const plants = objectsWhere(parking, (name) => name === "potted plant");
    expect(plants).toEqual([[1, 17], [1, 21], [1, 30], [1, 34]]);
    const benches = objectsWhere(parking, (name, imageId) => name === "bench" && imageId === GameImages.OBJ_BENCH);
    expect(benches).toEqual([[1, 18], [1, 19], [1, 20], [1, 31], [1, 32], [1, 33]]);
    for (let y = 23; y <= 28; y++) expect(objAt(parking, 1, y), `clear at 1,${y}`).toBeNull();
  });

  it("lays the bay tiles in the C#'s orientation: NS on the edge rows, EW everywhere else", () => {
    Session.get().ruleset = Ruleset.STILL_ALIVE;
    const { parking } = generateLevels();

    // **This is the assertion the method exists for.** The previous port note claimed
    // `PARKING_ASPHALT_NS` / `_EW` were unregistered tile models; they are registered at
    // `GameTiles.ts:402-403` (`= 133` and `= 134`), and the abandoned-car test at
    // `:10599` compares against *both* because both orientations occur.
    const ns = Models.tiles.get(TileID.PARKING_ASPHALT_NS)!;
    const ew = Models.tiles.get(TileID.PARKING_ASPHALT_EW)!;
    expect(ns.imageId).toBe(GameImages.TILE_PARKING_ASPHALT_NS);
    expect(ew.imageId).toBe(GameImages.TILE_PARKING_ASPHALT_EW);

    // The three edge runs (`:10574-10576`). **North-south on the top and bottom rows,
    // east-west on the right-hand column** — the two orientations are not
    // interchangeable and nothing in the geometry requires the swap.
    for (const y of [1, 49]) {
      for (const x of [6, 25, 47]) {
        expect(modelAt(parking, x, y), `edge row ${x},${y}`).toBe(ns);
        expect(modelAt(parking, x, y), `edge row ${x},${y}`).not.toBe(ew);
      }
    }
    for (let y = 2; y <= 48; y++) {
      expect(modelAt(parking, 49, y), `right column 49,${y}`).toBe(ew);
      expect(modelAt(parking, 49, y), `right column 49,${y}`).not.toBe(ns);
    }
    // Just outside the three runs the floor is plain asphalt, so the runs are bounded.
    expect(modelAt(parking, 5, 1), "west of the top row").not.toBe(ns);
    expect(modelAt(parking, 48, 1), "east of the top row").not.toBe(ns);
    expect(modelAt(parking, 48, 49), "east of the bottom row").not.toBe(ns);

    // Every one of the sixteen columns: two east-west bay strips of twenty-one tiles each,
    // a divider between them, starting `y == 4` in the north and `y == 27` in the south.
    expect(PARKING_COLUMNS).toHaveLength(16);
    for (const [columnX, columnY] of PARKING_COLUMNS) {
      for (let i = 0; i <= 20; ++i) {
        const y = columnY + i;
        expect(modelAt(parking, columnX, y), `bay ${columnX},${y}`).toBe(ew);
        expect(modelAt(parking, columnX + 2, y), `bay ${columnX + 2},${y}`).toBe(ew);
        // The divider is never a bay tile, in either orientation.
        const divider = modelAt(parking, columnX + 1, y);
        expect(divider, `divider ${columnX + 1},${y}`).not.toBe(ew);
        expect(divider, `divider ${columnX + 1},${y}`).not.toBe(ns);
      }
    }
    // A bay count, because the per-column loop is `i <= 20` and an off-by-one there would
    // show up as sixteen missing bays rather than as a shifted row.
    let bayTiles = 0;
    for (let x = 0; x < 51; x++) {
      for (let y = 0; y < 51; y++) if (modelAt(parking, x, y) === ew || modelAt(parking, x, y) === ns) bayTiles++;
    }
    // 16 columns * 2 strips * 21 rows, plus the 47-tile right column, plus the 42-tile
    // bottom row. The *top* row's 42 tiles are excluded by the C#'s own car rectangle but
    // they are still bay tiles, which is the asymmetry the next test pins.
    expect(bayTiles).toBe(16 * 2 * 21 + 47 + 42 + 42);
  });

  it("alternates a load-bearing pillar tile and an iron railing every fifth step", () => {
    Session.get().ruleset = Ruleset.STILL_ALIVE;
    const { parking } = generateLevels();

    const pillar = Models.tiles.get(TileID.WALL_PILLAR_CONCRETE)!;
    expect(pillar.imageId).toBe(GameImages.TILE_WALL_PILLAR_CONCRETE);

    // `if (i % 5 == 0) SetTileModelAt(x + 1, …, WALL_PILLAR_CONCRETE) else PlaceMapObjectAt(IronRailing)`
    // (`:10587-10590`) — **the pillar is a tile and the railing is an object**, which is
    // the whole reason the two are spelled differently and the only way to tell them
    // apart on a finished map.
    for (const [columnX, columnY] of PARKING_COLUMNS) {
      for (let i = 0; i <= 20; ++i) {
        const y = columnY + i;
        if (i % 5 === 0) {
          expect(modelAt(parking, columnX + 1, y), `pillar tile ${columnX + 1},${y}`).toBe(pillar);
          expect(objAt(parking, columnX + 1, y), `no object on a pillar ${columnX + 1},${y}`).toBeNull();
        } else {
          expect(modelAt(parking, columnX + 1, y), `railing is not a pillar tile ${columnX + 1},${y}`).not.toBe(pillar);
          const railing = objAt(parking, columnX + 1, y);
          expect(railing?.name, `railing ${columnX + 1},${y}`).toBe("iron railing");
          expect(railing?.imageId).toBe(GameImages.OBJ_RAILING);
        }
      }
    }
    // Five pillars and sixteen railings per column, sixteen columns.
    expect(objectsWhere(parking, (name) => name === "iron railing")).toHaveLength(16 * 16);
    let pillars = 0;
    for (let x = 0; x < 51; x++) {
      for (let y = 0; y < 51; y++) if (modelAt(parking, x, y) === pillar) pillars++;
    }
    expect(pillars).toBe(16 * 5);

    // **A railing is unbreakable, with zero hit points, and metal.** The default
    // `MapObject(name, imageID)` constructor gives it that, and it is the only reason a
    // railing cannot be cleared to open a route through the divider.
    const railing = objAt(parking, 10, 5)!;
    expect(railing.maxHitPoints).toBe(0);
    expect(railing.isBreakable).toBe(false);
    expect(railing.isMetal).toBe(true);
    expect(railing.isJumpable).toBe(true);
  });

  it("parks abandoned cars only on bay tiles, and not on the top row", () => {
    Session.get().ruleset = Ruleset.STILL_ALIVE;
    const { parking } = generateLevels();

    const ns = Models.tiles.get(TileID.PARKING_ASPHALT_NS)!;
    const ew = Models.tiles.get(TileID.PARKING_ASPHALT_EW)!;
    const cars = objectsWhere(parking, (name) => name === "abandoned car");
    expect(cars.length, "a car park with cars in it").toBeGreaterThan(0);

    // **The C#'s only test (`:10599`) is the tile model**, so this is the invariant that
    // says the fill rectangle and the bay layout agree: nothing off a bay gets a car.
    for (const [x, y] of cars) {
      const model = modelAt(parking, x, y);
      expect(model === ew || model === ns, `car at ${x},${y} is on a bay`).toBe(true);
    }
    // Both orientations occur, which is why the test in the reference accepts both.
    const orientations = new Set(cars.map(([x, y]) => (modelAt(parking, x, y) === ew ? "EW" : "NS")));
    expect(orientations, "cars stand both ways round").toEqual(new Set(["EW", "NS"]));

    // **`MapObjectFill(new Rectangle(6, 2, 44, 48))` stops at `y == 49`.** The bottom NS
    // row is inside it and the top NS row is one row outside, so the top row can hold a
    // car on the map and is the one row the generator never rolls for. The C#'s rectangle,
    // kept.
    for (let x = 6; x <= 47; x++) expect(objAt(parking, x, 1), `top row ${x},1`).toBeNull();
    const bottomRowCars = cars.filter(([, y]) => y === 49);
    expect(bottomRowCars.length, "the bottom row is inside the car rectangle").toBeGreaterThan(0);

    // A car is unbreakable, `UNINFLAMMABLE`, and — unlike the dealership's display cars —
    // carries 30 to 98 units of fuel, which is what makes it worth siphoning.
    const car = objAt(parking, cars[0]![0], cars[0]![1])!;
    expect(car.isBreakable).toBe(false);
    expect(car.isFlammable).toBe(false);
    expect(car).toBeInstanceOf(Car);
    expect((car as Car).fuelUnits).toBeGreaterThanOrEqual(30);
    expect((car as Car).fuelUnits).toBeLessThanOrEqual(98);
    // The four-sprite `CARS` table, the same one the dealership draws from.
    expect([GameImages.OBJ_CAR1, GameImages.OBJ_CAR2, GameImages.OBJ_CAR3, GameImages.OBJ_CAR4]).toContain(car.imageId);
  });

  it("rings each power room with generators, on the eight-neighbour wall count", () => {
    Session.get().ruleset = Ruleset.STILL_ALIVE;
    const { parking } = generateLevels();

    // Two zones, both named `power room`, at `Rectangle(1,1,3,10)` and
    // `Rectangle(1,40,3,10)` (`:10540`, `:10558`).
    const rooms = parking.zones.filter((z) => z.name.startsWith("power room@"));
    expect(rooms).toHaveLength(2);
    expect(rooms.map((z) => [z.bounds.left, z.bounds.top, z.bounds.width, z.bounds.height])).toEqual([
      [1, 1, 3, 10],
      [1, 40, 3, 10],
    ]);

    // Each door is a three-tile run of wall with an iron door in the middle.
    for (const y of [11, 39]) {
      expect(modelAt(parking, 1, y), `power room wall 1,${y}`).toBe(Models.tiles.get(TileID.WALL_CONCRETE));
      expect(modelAt(parking, 3, y), `power room wall 3,${y}`).toBe(Models.tiles.get(TileID.WALL_CONCRETE));
      expect(objAt(parking, 2, y)?.name, `iron door 2,${y}`).toBe("iron door");
      expect(objAt(parking, 2, y)?.isAn, "an iron door takes an article").toBe(true);
    }

    // **An L of twenty-one, not a thirty-tile grid.** `CountAdjWalls` is
    // `CountForEachAdjacent` over all *eight* neighbours (`MapGenerator.cs:405-420`), so
    // a corner counts three walls and both side columns of each room qualify for all ten
    // rows. Only the far-end tile of the middle column qualifies; the rest of the middle
    // column is the two-tile walkway in from the door. Stated as positions so a port that
    // reached for `Direction.COMPASS_4` — which would place none at all — fails loudly.
    const generators = objectsWhere(parking, (name) => name === "power generator");
    expect(generators).toHaveLength(2 * 21);
    for (const [y0, farEnd] of [[1, 1], [40, 49]] as [number, number][]) {
      const want: [number, number][] = [];
      for (let i = 0; i < 10; i++) want.push([1, y0 + i]);
      want.push([2, farEnd]);
      for (let i = 0; i < 10; i++) want.push([3, y0 + i]);
      const got = generators
        .filter(([, y]) => y >= y0 && y < y0 + 10)
        .sort((a, b) => a[0] - b[0] || a[1] - b[1]);
      expect(got, `the L in the room at 1,${y0}`).toEqual(want);
    }
    // A generator is metal and a two-state object that starts off.
    const generator = objAt(parking, 1, 1)!;
    expect(generator.isMetal).toBe(true);
    expect((generator as PowerGenerator).isOn).toBe(false);
  });

  it("builds the same two levels twice from one seed, and different ones from different seeds", () => {
    Session.get().ruleset = Ruleset.STILL_ALIVE;
    const first = generateLevels();
    const second = generateLevels();
    expect(fingerprint(first.upper)).toBe(fingerprint(second.upper));
    expect(fingerprint(first.parking)).toBe(fingerprint(second.parking));

    // The dice are really being spent: the counters' three rolls per tile, the cinema
    // seats' 20%, the abandoned cars' 20% and two more dice each.
    const prints = new Set([1, 2, 3, 4, 5].map((s) => fingerprint(generateLevels(s).upper)));
    expect(prints.size).toBeGreaterThan(1);
    const carParks = new Set([1, 2, 3, 4, 5].map((s) => fingerprint(generateLevels(s).parking)));
    expect(carParks.size).toBeGreaterThan(1);
  });

  it("still reaches both levels through the six stairways, onto floor", () => {
    Session.get().ruleset = Ruleset.STILL_ALIVE;
    const { upper, parking, ground, district } = generateLevels();

    expect(district.countMaps).toBe(3);

    // `MakeShoppingMall`'s six `AddExit` pairs: four up to the `+1` level and two down to
    // the `-1`. Asserted from the ground floor *and* from the far end, because the exits
    // are added after both levels have been furnished and a level that filled its own
    // stair tile would still pass a one-sided check.
    //
    // The ground-floor tiles are offset from `mallBlock.InsideRect` — the block at
    // `(1, 1, 48, 48)` insets twice, so `l == 3` and `t == 3` and the six stairs land on
    // `(16, 24)`, `(16, 25)`, `(32, 24)`, `(32, 25)`, `(24, 24)` and `(24, 25)`.
    const pairs: [number, number, number, number, GameMap][] = [
      [16, 24, 18, 25, upper],
      [16, 25, 18, 26, upper],
      [32, 24, 34, 25, upper],
      [32, 25, 34, 26, upper],
      [24, 24, 1, 25, parking],
      [24, 25, 1, 26, parking],
    ];
    expect(pairs).toHaveLength(6);

    for (const [gx, gy, lx, ly, target] of pairs) {
      const down = ground.getExitAt(new Point(gx, gy));
      expect(down, `exit at ${gx},${gy}`).not.toBeNull();
      expect(down!.isAnAIExit, `exit at ${gx},${gy} is an AI exit`).toBe(true);
      expect(down!.toMap, `exit at ${gx},${gy} target`).toBe(target);

      const up = target.getExitAt(new Point(lx, ly));
      expect(up, `far end at ${lx},${ly} on ${target.name}`).not.toBeNull();
      expect(up!.toMap, `far end at ${lx},${ly} returns to the surface`).toBe(ground);

      // **The far tile is walkable.** This is the assertion the fit-outs make possible
      // and the shell could not: a stairway that lands inside a shelf, a counter or a
      // curtain wall is a broken link in the map graph, and nothing else in the suite
      // would report it.
      const landing = target.getTileAt(lx, ly)!;
      expect(landing.model.isWalkable, `${target.name} landing ${lx},${ly} is walkable`).toBe(true);
      expect(target.getMapObjectAt(lx, ly), `${target.name} landing ${lx},${ly} is clear`).toBeNull();
    }
  });
});